CXX = g++
ARCH = -mtune=generic
VERSION = 0.7.9
#	ARCH = -march=core2
#	ARCH = -march=native


# Use O1 for debuiggging so it's not totally slow.
DBGFLAGS = -O1 -ggdb -U_FORTIFY_SOURCE
COFLAGS = $(ARCH) -O2 -pipe
CXXFLAGS = -DBS_VERSION=\"$(VERSION)\" -Wall $(COFLAGS)
# -Wvla does not work with old gcc
# -ffast-math segfaults with old gcc, don't use.
#LDFLAGS = -Wl,-gc-sections
BOOSTFLAGS = -I .
#OPENMP = -fopenmp -DSUPPORT_OPENMP
OPENMP = 

PROGRAMS = \
   convertSamples \
   extractSamples \
   getFoldChange \
   getPPLR \
   transposeLargeFile \
   gtftool \
   bitseq

all: $(PROGRAMS)

COMMON_DEPS = ArgumentParser.o common.o FileHeader.o misc.o MyTimer.o TranscriptInfo.o PosteriorSamples.o

COMMAND_OBJECTS = estimateExpression.o estimateVBExpression.o parseAlignment.o estimateDE.o estimateFCProb.o estimateHyperPar.o getGeneExpression.o getVariance.o getWithinGeneExpression.o

# PROGRAMS:
convertSamples: convertSamples.cpp $(COMMON_DEPS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) convertSamples.cpp $(COMMON_DEPS) -o convertSamples

extractSamples: extractSamples.cpp $(COMMON_DEPS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) extractSamples.cpp $(COMMON_DEPS) -o extractSamples

getFoldChange: getFoldChange.cpp $(COMMON_DEPS) 
	$(CXX) $(CXXFLAGS) $(LDFLAGS) getFoldChange.cpp $(COMMON_DEPS) -o getFoldChange

getPPLR: getPPLR.cpp $(COMMON_DEPS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) getPPLR.cpp $(COMMON_DEPS) -o getPPLR

#parseAlignment: parseAlignment.cpp $(COMMON_DEPS) ReadDistribution.o samtools/sam.o TranscriptExpression.o TranscriptSequence.o
#	$(CXX) $(CXXFLAGS) $(OPENMP) $(LDFLAGS) -pthread parseAlignment.cpp $(COMMON_DEPS) ReadDistribution.o samtools/*.o TranscriptExpression.o TranscriptSequence.o -lz -o parseAlignment

transposeLargeFile: transposeLargeFile.cpp $(COMMON_DEPS) transposeFiles.o
	$(CXX) $(CXXFLAGS) $(LDFLAGS) transposeLargeFile.cpp $(COMMON_DEPS) transposeFiles.o -o transposeLargeFile

gtftool: gtftool.cpp $(COMMON_DEPS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) gtftool.cpp $(COMMON_DEPS) -o gtftool

bitseq: bitseq.cpp $(COMMON_DEPS) $(COMMAND_OBJECTS) ReadDistribution.o samtools/sam.o TranscriptExpression.o TranscriptSequence.o
	$(CXX) $(CXXFLAGS) $(BOOSTFLAGS) $(OPENMP) $(LDFLAGS) -pthread bitseq.cpp $(COMMON_DEPS) $(COMMAND_OBJECTS) SimpleSparse.o CollapsedSampler.o GibbsParameters.o GibbsSampler.o lowess.o ReadDistribution.o Sampler.o TagAlignments.o TranscriptExpression.o TranscriptSequence.o transposeFiles.o VariationalBayes.o samtools/*.o -lz -o bitseq

# COMMANDS:
estimateDE.o: estimateDE.cpp
	$(CXX) $(CXXFLAGS) $(BOOSTFLAGS) -c estimateDE.cpp

estimateExpression.o: estimateExpression.cpp
	$(CXX) $(CXXFLAGS) $(BOOSTFLAGS) $(OPENMP) -c estimateExpression.cpp 

estimateVBExpression.o: estimateVBExpression.cpp
	$(CXX) $(CXXFLAGS) $(BOOSTFLAGS) $(OPENMP) -c estimateVBExpression.cpp 

parseAlignment.o: parseAlignment.cpp
	$(CXX) $(CXXFLAGS) $(BOOSTFLAGS) $(OPENMP) -c parseAlignment.cpp 

estimateFCProb.o: estimateFCProb.cpp
	$(CXX) $(CXXFLAGS) -c estimateFCProb.cpp

estimateHyperPar.o: estimateHyperPar.cpp
	$(CXX) $(CXXFLAGS) $(BOOSTFLAGS) -c estimateHyperPar.cpp

getGeneExpression.o: getGeneExpression.cpp
	$(CXX) $(CXXFLAGS) -c getGeneExpression.cpp

getVariance.o: getVariance.cpp
	$(CXX) $(CXXFLAGS) -c getVariance.cpp

getWithinGeneExpression.o: getWithinGeneExpression.cpp
	$(CXX) $(CXXFLAGS) -c getWithinGeneExpression.cpp

# LIBRARIES:
ArgumentParser.o: ArgumentParser.cpp ArgumentParser.h
	$(CXX) $(CXXFLAGS) -ffunction-sections -fdata-sections -c ArgumentParser.cpp

CollapsedSampler.o: CollapsedSampler.cpp CollapsedSampler.h GibbsParameters.h Sampler.h
	$(CXX) $(CXXFLAGS) $(BOOSTFLAGS) -c CollapsedSampler.cpp

FileHeader.o: common.h misc.h FileHeader.cpp FileHeader.h
	$(CXX) $(CXXFLAGS) $(BOOSTFLAGS) -ffunction-sections -fdata-sections -c FileHeader.cpp

GibbsSampler.o: GibbsSampler.cpp GibbsSampler.h GibbsParameters.h Sampler.h
	$(CXX) $(CXXFLAGS) $(BOOSTFLAGS) -c GibbsSampler.cpp

misc.o: ArgumentParser.h PosteriorSamples.h misc.cpp misc.h
	$(CXX) $(CXXFLAGS) -ffunction-sections -fdata-sections -c misc.cpp

MyTimer.o: MyTimer.h MyTimer.cpp
	$(CXX) $(CXXFLAGS) -ffunction-sections -fdata-sections -c MyTimer.cpp

PosteriorSamples.o: PosteriorSamples.cpp PosteriorSamples.h FileHeader.h
	$(CXX) $(CXXFLAGS) -ffunction-sections -fdata-sections -c PosteriorSamples.cpp

ReadDistribution.o: ReadDistribution.cpp ReadDistribution.h TranscriptExpression.h TranscriptInfo.h TranscriptSequence.h 
	$(CXX) $(CXXFLAGS) $(OPENMP) -c ReadDistribution.cpp

Sampler.o: Sampler.cpp Sampler.h GibbsParameters.h
	$(CXX) $(CXXFLAGS) $(BOOSTFLAGS) -c Sampler.cpp

SimpleSparse.o: SimpleSparse.cpp SimpleSparse.h
	$(CXX) $(CXXFLAGS) $(OPENMP) -c SimpleSparse.cpp

VariationalBayes.o: VariationalBayes.cpp VariationalBayes.h SimpleSparse.h
	$(CXX) $(CXXFLAGS) $(BOOSTFLAGS) $(OPENMP) -c VariationalBayes.cpp 

common.o: common.cpp common.h
GibbsParameters.o: ArgumentParser.h GibbsParameters.cpp GibbsParameters.h
lowess.o: lowess.cpp lowess.h
TagAlignments.o: TagAlignments.cpp TagAlignments.h
TranscriptExpression.o: TranscriptExpression.cpp TranscriptExpression.h
TranscriptInfo.o: TranscriptInfo.cpp TranscriptInfo.h
TranscriptSequence.o: TranscriptSequence.cpp TranscriptSequence.h
transposeFiles.o: transposeFiles.cpp transposeFiles.h FileHeader.h

# EXTERNAL LIBRARIES:
samtools/sam.o:
	make --directory samtools

# CLEAN:
clean:
	rm *.o $(PROGRAMS)

clean-all:
	rm samtools/*.o *.o $(PROGRAMS)

